version: "3"
services:
  backend:
    image: backend
    build:
      context: .
    ports:
      - "7000:7000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      PORT: 7000
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}?schema=users
  
  migration:
    image: backend:latest
    command: >
      bash ./scripts/wait-for-it.sh db:5432 -- npm run db:migrate:deploy
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}?schema=users
    links:
      - db
    depends_on:
      - db
      - backend

  db:
    image: postgres:13.4
    container_name: postgresql
    ports:
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    env_file:
      - .env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always